name: Lint and Test

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  checks:
    name: Main Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.7.14
      - name: Run lint
        run: deno lint
      - name: Run format check
        run: deno fmt --check
  e2e:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.7.14
      - name: Run tests
        run: |
          deno task test
          deno task e2e
